// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysResourceRelated is the golang structure for table sys_resource_related.
type SysResourceRelated internal.SysResourceRelated

// Fill with you ideas below.