// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysDoc is the golang structure for table sys_doc.
type SysDoc internal.SysDoc

// Fill with you ideas below.