// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysDoc is the golang structure for table sys_doc.
type SysDoc struct {
    DocId      int64       `orm:"doc_id,primary" json:"docId"`      //   
    Title      string      `orm:"title"          json:"title"`      //   
    Content    string      `orm:"content"        json:"content"`    //   
    CreateTime *gtime.Time `orm:"create_time"    json:"createTime"` //   
    UpdateTime *gtime.Time `orm:"update_time"    json:"updateTime"` //   
}