// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysResourceRelated is the golang structure for table sys_resource_related.
type SysResourceRelated struct {
    ResourceId int64  `orm:"resource_id" json:"resourceId"` //   
    Module     string `orm:"module"      json:"module"`     //   
    RelatedId  int64  `orm:"related_id"  json:"relatedId"`  //   
}